### ISSUE TITLE
How can I push the input (*.sdf and options) to run the model of scaffold_elaboration in DEVELOP?

### ISSUE THREAD

**Issue by Jooyun1983** [fimrie/DEVELOP#1]
I installed DEVELOP according to the guideline. And I checked running well for "the generation of molecules with a pretrained model using the first setting, use: (example code, linker_design) ........" BUT, I would like to use the model of scaffold_elaboration, so I replaced all the keyword "linker_design" in the example code with "scaffold_elaboration".

python DEVELOP.py --dataset zinc --restore models/linker_design/pretrained_DEVELOP_model.pickle.......
>>>> python DEVELOP.py
--dataset zinc --restore models/scaffold_elaboration/pretrained_DEVELOP_model.pickle
--config '{"generation": true, "number_of_generation_per_valid": 10, "batch_size": 1,
"train_file": "data/scaffold_elaboration/molecules_casf_test.json",
"train_struct_file": "data/scaffold_elaboration/casf_test_structs.types",
"valid_file": "data/scaffold_elaboration/molecules_casf_test.json",
"valid_struct_file": "data/scaffold_elaboration/casf_test_structs.types",
"struct_data_root": "./data/scaffold_elaboration/"}'    >>>> (I checked all file path.)

[ENTER]----------------------------------------------------------------------------------
Traceback (most recent call last):
  File "DEVELOP.py", line 1268, in <module>
    model.train()
  File "/data/DEVELOP/DEVELOP-main/GGNN_DEVELOP.py", line 384, in train
    self.generate_new_graphs(self.valid_data, self.valid_struct_data)
  File "DEVELOP.py", line 1191, in generate_new_graphs
    maximum_length, generated_all_smiles, elements, count, cnn_input)
  File "DEVELOP.py", line 1058, in generate_graph_with_state
    predicted_node_symbol_prob = self.get_node_symbol(node_symbol_batch_feed_dict)
  File "DEVELOP.py", line 920, in get_node_symbol
    result = self.sess.run(fetch_list, feed_dict=batch_feed_dict)
  File "/home/jylee/anaconda3/envs/DEVELOP_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/jylee/anaconda3/envs/DEVELOP_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 3) for Tensor 'graph_model/abs_dist:0', which has shape '(?, 5)'
> /home/jylee/anaconda3/envs/DEVELOP_env/lib/python3.7/site-packages/tensorflow/python/client/session.py(1149)_run()
-> str(subfeed_t.get_shape())))
(Pdb)
----------------------------------------------------------------------------------------------
How can I push the input (*.sdf and options) to run the model of scaffold_elaboration in DEVELOP?

**Comment by fimrie** [comment]
Hi, this issue was caused due to the pretrained model including values of (0,0) for the distance and angle information (DEVELOP only uses the distance and angle for linker design). However, these values were not being added by the pre-processing script. I have amended the pre-processing script included in this repo to add those values by default so that the output can be used with the provided model. However, if you are training your own model, these values are not required. They can be omitted by adding the "--no_dummy_info" flag when running prepare_data_scaffold_elaboration.py

This should fix the issue you were having. Please let me know if you have any additional queries or questions.
